### ISSUE TITLE
TrueOS18.03 Ports iocage default IP addr: freebsd.org

### ISSUE THREAD

**Issue by mrT55** [trueos/trueos-ports#33]
host: TrueOS 18.03
sysutils/py36-iocage-0.9.10
While setting up iocage,
Enter the cmd:
```
sudo iocage activate tank
         ZFS pool 'tank' successfully activated.

sudo iocage fetch
             ...
         * Updating 11.2-RELEASE to the latest patch level...
         Looking up update.FreeBSD.org mirrors... 2 mirrors found.
         Fetching public key from update5.freebsd.org... done.
         Fetching metadata signature for 11.2-RELEASE from update5.freebsd.org... done.
           ...
```

And discovered  it was fetching from: https://download.freebsd.org/ftp/releases/amd64/11.2-RELEASE
instead of one of the trueos.org IP addresses.

```
cd /usr/local/lib/python3.6/site-packages/iocage
$ grep -rnE "freebsd\.org" * 
    cli/fetch.py:79:    default="download.freebsd.org",
    lib/ioc_create.py:428:                                repo="pkg.freebsd.org", site="FreeBSD"):
    lib/ioc_fetch.py:61:                 server="download.freebsd.org",
    lib/ioc_fetch.py:124:        _eol = "https://www.freebsd.org/security/unsupported.html"
    lib/ioc_fetch.py:338:            if self.server == "download.freebsd.org":
    lib/ioc_fetch.py:569:                    if self.server == "https://download.freebsd.org":
    lib/ioc_fetch.py:1371:        if self.server == "download.freebsd.org":
    lib/iocage.py:924:                if kwargs["server"] == "download.freebsd.org":
```
```
grep -rnE "freebsd-update" * 
    cli/update.py:33:    help="Run freebsd-update to update a specified "
    cli/upgrade.py:33:    help="Run freebsd-update to upgrade a specified"
    lib/ioc_upgrade.py:79:        if not os.path.isfile(f"{self.path}/etc/freebsd-update.conf"):
    lib/ioc_upgrade.py:85:            "/master/usr.sbin/freebsd-update/freebsd-update.sh"
    lib/ioc_upgrade.py:98:                    f"{self.path}/var/db/freebsd-update/", "-f",
    lib/ioc_upgrade.py:99:                    f"{self.path}/etc/freebsd-update.conf",
    lib/ioc_upgrade.py:232:                f"{self.path}/var/db/freebsd-update/", "-f",
    lib/ioc_upgrade.py:233:                f"{self.path}/etc/freebsd-update.conf", "-r", self.new_release,
    lib/ioc_upgrade.py:256:        Replaces freebsd-update.conf's default Components configuration to not
    lib/ioc_upgrade.py:259:        f = f"{self.path}/etc/freebsd-update.conf"
    lib/ioc_fetch.py:814:        """This calls 'freebsd-update' to update the fetched RELEASE."""
    lib/ioc_fetch.py:857:        if os.path.isfile(f"{new_root}/etc/freebsd-update.conf"):
    lib/ioc_fetch.py:860:                    "/master/usr.sbin/freebsd-update/freebsd-update.sh"
    lib/ioc_fetch.py:869:                fetch_name = f"{new_root}/usr/sbin/freebsd-update"
    lib/ioc_fetch.py:873:                f"{new_root}/var/db/freebsd-update/", "-f",
    lib/ioc_fetch.py:874:                f"{new_root}/etc/freebsd-update.conf",
    lib/ioc_fetch.py:886:                    f"{new_root}/var/db/freebsd-update/", "-f",
    lib/ioc_fetch.py:887:                    f"{new_root}/etc/freebsd-update.conf", "install"
```
I suspect that trueos.org did not intend for that.

To work-around the above condition, I tried:
```
sudo iocage fetch --server download.trueos.org/unstable/amd64/dist/
     Traceback (most recent call last):
       File "/usr/local/bin/iocage", line 10, in <module>
         sys.exit(cli())
       File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
         return self.main(*args, **kwargs)
       File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
         rv = self.invoke(ctx)
       File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
         return _process_result(sub_ctx.command.invoke(sub_ctx))
       File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
         return ctx.invoke(self.callback, **ctx.params)
       File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
         return callback(*args, **kwargs)
       File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 166, in cli
         ioc.IOCage(exit_on_error=True).fetch(**kwargs)
       File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 993, in fetch
         silent=self.silent, **kwargs).fetch_release()
       File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 234, in fetch_release
         rel = self.fetch_http_release(eol, _list=_list)
       File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 440, in fetch_http_release
         req.raise_for_status()
       File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 937, in raise_for_status
         raise HTTPError(http_error_msg, response=self)
     
     requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://download.trueos.org/unstable/amd64/dist//ftp/releases/amd64

```

**Comment by miwi-fbsd** [comment]
Hi,

TrueOS 18.03 is no longer supported, please upgrade to 18.06.

Thanks.
