### ISSUE TITLE
/sysutils/iocage

### ISSUE THREAD

**Issue by ichibiri** [trueos/trueos-ports#54]
In:
> FreeBSD trident-1496 12.0-CURRENT FreeBSD 12.0-CURRENT #0: Mon Sep 24 21:00:29 UTC 2018
 
After **pkg install py36-iocage**
When invoking **iocage**

```
root@trident-1496:/usr/home/gnao # iocage
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 6, in <module>
    from iocage.main import cli
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 37, in <module>
    import iocage.lib.ioc_check as ioc_check
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_check.py", line 29, in <module>
    import iocage.lib.ioc_json
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 37, in <module>
    import iocage.lib.ioc_create
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_create.py", line 34, in <module>
    import iocage.lib.ioc_exec
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_exec.py", line 30, in <module>
    import iocage.lib.ioc_start
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_start.py", line 31, in <module>
    import netifaces
ModuleNotFoundError: No module named 'netifaces'

```
_no go!_

_and_

**pkg install iocage**

```
Updating TrueOS-ports repository catalogue...
TrueOS-ports repository is up to date.
Updating TrueOS-base repository catalogue...
TrueOS-base repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'iocage' have been found in the repositories
```
How would one know which pkg or port installs what ?  I know it as **py36-iocage** :)
Tho, **pkg install py36-iocage**  doesn't install iocage correctly :(
I think that ... , I had to **make py36-iocage** from ports, in TrueOS-18.3, for iocage to work.

**Comment by miwi-fbsd** [comment]
Hi,

Is this problem still existing?

**Comment by miwi-fbsd** [comment]
Close with feedback timeout
